--consulta para trazer ocorrencias com animais--
SELECT
    T.NUMOCORRENCIA,
    PP.DESCRICAO AS 'Caracteristicas da Via',
    EP.DESCRICAO AS 'Caracteristicas do Entorno',
    CONVERT(VARCHAR(12),
    T.DATAOCORRENCIA,
    103) AS 'Data',
    CONVERT(VARCHAR(12),
    O.HORAOCORRENCIA,
    108) AS HORA,
    R.SIGLARODOVIA AS RODOVIA,
    CONCAT(O.KM,
    '+',
    O.KMCOMP) AS KM,
    S.SENTIDO AS 'Pista',
    A.GENERO AS 'Classificação',
    A.GRUPO AS 'Grupo',
    A.ANIMAL AS 'Nome Popular',
    A.ESPECIE AS 'Nome Científico',
    T.QTD AS 'Quantidade',
    OT.DESCROCORRENCIA AS 'Tipo de Ocorrência',
    TPA.PROVANIMAL AS 'Destinação',
    OBS.OBSERVACAO
FROM
    TABANIMAIS T
    LEFT JOIN TAUXANIMAIS A
    ON T.CODANIMAL = A.CODANIMAL
    LEFT JOIN TABOCORRENCIAS O
    ON T.NUMOCORRENCIA = O.NUMOCORRENCIA
    AND T.DATAOCORRENCIA = O.DATAOCORRENCIA
    LEFT JOIN TAUXTIPOSOCORRENCIAS OT
    ON O.CODTIPOOCORRENCIA = OT.CODTIPOOCORRENCIA
    LEFT JOIN TAUXANIMAISPERFILPISTA PP
    ON T.CODPERFILPISTA = PP.CODPERFILPISTA
    LEFT JOIN TAUXANIMAISENTORNOPISTA EP
    ON T.CODENTORNOPISTA = EP.CODENTORNOPISTA
    LEFT JOIN TAUXRODOVIAS R
    ON O.CODRODOVIA = R.CODRODOVIA
    LEFT JOIN TAUXSENTIDOS S
    ON O.CODSENTIDO = S.CODSENTIDO
    LEFT JOIN TAUXTIPOSPROVANIMAIS TPA
    ON T.CODPROVANIMAL = TPA.CODPROVANIMAL
    LEFT JOIN TAUXANIMAISDESTINOS D
    ON T.DESTINO = D.CODDESTINO
    LEFT JOIN TABOCORRENCIASOBS OBS
    ON O.NUMOCORRENCIA = OBS.NUMOCORRENCIA
    AND O.DATAOCORRENCIA = OBS.DATAOCORRENCIA
WHERE
    T.DATAOCORRENCIA BETWEEN '2023-01-01'
    AND '2023-01-31'
ORDER BY
    DATA,
    NUMOCORRENCIA