SELECT
    C.NUMSOLICITACAO,
    CONVERT(VARCHAR(12), C.DATASOLICITACAO, 103) AS DATASOLICITACAO,
    CO.ORIGEMCONSERV,
    C.OBSERVACOES,
    T.TIPOCONSERVACAO AS TIPO,
    S.CONSERVSTATUS AS 'STATUS',
    C.PRAZO,
    R.RESPONSAVEL,
    CONVERT(VARCHAR(12), C.DATAINS, 103) AS DATAINSERÇÃO,
    CONVERT(VARCHAR(12), C.DATAENC, 103) AS DATAENCERRAMENTO,
    CONVERT(VARCHAR(12), C.DATAPRAZOFINAL, 103) AS PRAZOFINAL
FROM
    TABCONSERVACAO C
LEFT JOIN TAUXCONSERVORIGEM CO
    ON CO.CODORIGEMCONSERV = C.CODORIGEMSOLICITACAO
LEFT JOIN TAUXCONSERVRESP R
    ON R.CODRESP = C.CODRESP
LEFT JOIN TAUXCONSERVTIPOS T
    ON T.CODTIPOCONSERVACAO = C.CODTIPOCONSERV
LEFT JOIN TAUXCONSERVSTATUS S
    ON S.CODSTATUS = C.CODSTATUS
WHERE
    C.DATASOLICITACAO BETWEEN '2023-01-01' AND DATEADD(DAY, -1, GETDATE())
    AND CO.ORIGEMCONSERV IN ('ARTESP');
