SELECT
	C.NUMSOLICITACAO,
	CONVERT (VARCHAR(12), C.DATASOLICITACAO, 103) AS DATASOLICITACAO,
	CO.ORIGEMCONSERV,
	C.OBSERVACOES,
	T.TipoConservacao AS TIPO,
	S.ConservStatus AS 'STATUS',
	C.PRAZO,
	R.RESPONSAVEL,
	CONVERT(VARCHAR(12), C.DtProgini, 103) AS DATAPROGINI,
	CONVERT(VARCHAR(12), C.DtProgFim, 103) AS DATAPROGFIM,
	CONVERT(VARCHAR(12), C.DtExecIni, 103) AS DATAEXECINI,
	CONVERT(VARCHAR(12), C.DtExecFim, 103) AS DATAFIMEXEC,
	CONVERT(VARCHAR(12), C.DATAINS, 103) AS DATAINSERÇÃO,
	CONVERT(VARCHAR(12), C.DATAENC,	103) AS DATAENCERRAMENTO,
	CONVERT(VARCHAR(12), C.DATAPRAZOFINAL, 103) AS PRAZOFINAL
FROM
	TABCONSERVACAO C
	LEFT JOIN TAUXCONSERVORIGEM CO ON CO.CODORIGEMCONSERV = C.CODORIGEMSOLICITACAO
	LEFT JOIN TAUXCONSERVRESP R ON R.CODRESP = C.CODRESP
	LEFT JOIN TAuxConservTipos T ON T.CodTipoConservacao = C.CodTipoConserv
	LEFT JOIN TAuxConservStatus S ON S.CodStatus = C.CodStatus
WHERE
	C.DATASOLICITACAO BETWEEN '2022-01-01' AND DATEADD(DAY,	-1,	GETDATE())
	AND co.OrigemConserv = 'ARTESP'
	AND C.CodStatus <> '3'
	--C.DataSolicitacao BETWEEN '2022-01-01' AND '2023-10-06'

	UNION ALL

SELECT
	C.NUMSOLICITACAO,
	CONVERT (VARCHAR(12), C.DATASOLICITACAO, 103) AS DATASOLICITACAO,
	CO.ORIGEMCONSERV,
	C.OBSERVACOES,
	T.TipoConservacao AS TIPO,
	S.ConservStatus AS 'STATUS',
	C.PRAZO,
	R.RESPONSAVEL,
	CONVERT(VARCHAR(12), C.DtProgini, 103) AS DATAPROGINI,
	CONVERT(VARCHAR(12), C.DtProgFim, 103) AS DATAPROGFIM,
	CONVERT(VARCHAR(12), C.DtExecIni, 103) AS DATAEXECINI,
	CONVERT(VARCHAR(12), C.DtExecFim, 103) AS DATAFIMEXEC,
	CONVERT(VARCHAR(12), C.DATAINS, 103) AS DATAINSERÇÃO,
	CONVERT(VARCHAR(12), C.DATAENC,	103) AS DATAENCERRAMENTO,
	CONVERT(VARCHAR(12), C.DATAPRAZOFINAL, 103) AS PRAZOFINAL
FROM
	TabConservacaoAB C
	LEFT JOIN TAUXCONSERVORIGEM CO ON CO.CODORIGEMCONSERV = C.CODORIGEMSOLICITACAO
	LEFT JOIN TAUXCONSERVRESP R ON R.CODRESP = C.CODRESP
	LEFT JOIN TAuxConservTipos T ON T.CodTipoConservacao = C.CodTipoConserv
	LEFT JOIN TAuxConservStatus S ON S.CodStatus = C.CodStatus
WHERE
	C.DATASOLICITACAO BETWEEN '2022-01-01' AND DATEADD(DAY,	-1,	GETDATE())
	AND co.OrigemConserv = 'ARTESP'
	AND C.CodStatus <> '3'
	--C.DataSolicitacao BETWEEN '2022-01-01' AND '2023-10-06'
