--CONSULTA DE PROVIDENCIAS
SELECT
    CONCAT(T.NUMOCORRENCIA,	'-', CONVERT(VARCHAR(12), T.DATAOCORRENCIA, 103)) AS IDOCORRENCIA,
    T.NUMOCORRENCIA,
    CONVERT(VARCHAR(12), T.DATAOCORRENCIA, 103) AS DATAOCORRENCIA,
    J.PROVIDENCIA
FROM
    TABOCORRENCIAS T
    INNER JOIN TABPROVIDENCIASTOMADAS P ON P.NUMOCORRENCIA = T.NUMOCORRENCIA AND P.DATAOCORRENCIA = T.DATAOCORRENCIA
    INNER JOIN TAUXTIPOSPROVIDENCIAS J
    ON J.CODPROVIDENCIA = P.CODPROVIDENCIA
WHERE
    T.DATAOCORRENCIA BETWEEN '2010-07-01'
    AND DATEADD(DAY, -1, GETDATE())