SELECT
    CONCAT(V.NUMOCORRENCIA, '-', CONVERT(VARCHAR(12), V.DATAOCORRENCIA, 103)) AS IDOCORRENCIA,
    V.NUMOCORRENCIA,
    CONVERT(VARCHAR(12), V.DATAOCORRENCIA, 103) AS DATAOCORRENCIA,
    NUMVEICULO,
    NUMVITIMA,
    V.CODCONDICAO,
    CASE V.CODCONDICAO
        WHEN -1 THEN 'Não informado'
        WHEN 0 THEN 'Aparentemente Ileso'
        WHEN 1 THEN 'Leve'
        WHEN 2 THEN 'Moderado'
        WHEN 5 THEN 'Grave'
        WHEN 7 THEN 'Óbito'
        WHEN 8 THEN 'PCR-Reanimação'
        WHEN 9 THEN 'Morte Evidente'
    END AS CONDICAO,
    V.IDADE,
    V.SEXO,
    POSICOES,
    IIF(V.SUSPEITAETILISMO = 0, 'NÃO', 'SIM') AS SUSPEITAETILISMO
FROM
    TABVITIMAS V
    OUTER APPLY (
        SELECT STUFF((
                SELECT '; ' + P.DESCRPOSICAO
                FROM TAUXVITPOSICOES P
                WHERE P.CODTIPOPOSICAO = V.POSICAOORIGINAL
                FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),
            1, 2, '') AS POSICOES
    ) X
WHERE
    V.DATAOCORRENCIA BETWEEN '2023-01-01' AND DATEADD(DAY, -1, GETDATE())
