--CONSULTA DE RECURSOS
SELECT
	CONCAT(T.NUMOCORRENCIA,	'-', CONVERT(VARCHAR(12), T.DATAOCORRENCIA,	103)) AS IDOCORRENCIA,
    T.NUMOCORRENCIA,
    CONVERT (VARCHAR(12), T.DATAOCORRENCIA, 103) AS DATAOCORRENCIA,
    A.PREFIXO AS RECURSOACIONADO,
    TA.TIPOATENDIMENTO,
    CONVERT (VARCHAR(8), R.HORAACIONAMENTO, 108) AS HORAACIONAMENTO,
    CONVERT (VARCHAR(8), R.HORACHEGADA, 108) AS HORACHEGADA
FROM
    TABOCORRENCIAS T
    LEFT JOIN TABRECURSOSACIONADOS R
    ON R.NUMOCORRENCIA = T.NUMOCORRENCIA
    AND R.DATAOCORRENCIA = T.DATAOCORRENCIA
    LEFT JOIN TAUXRECURSOS A
    ON A.CODRECURSO = R.CODRECURSO
    LEFT JOIN TAuxTiposAtendimentos TA
    ON TA.CODTIPOATENDIMENTO = R.CODTIPOATEND
WHERE
    T.DATAOCORRENCIA BETWEEN '2023-01-01' AND DATEADD(DAY, -1, GETDATE())
ORDER BY
    DATAOCORRENCIA,
    NUMOCORRENCIA,
    HORAACIONAMENTO