--CONSULTA DE VEÍCULOS ENVOLVIDOS
SELECT
	V.NUMOCORRENCIA,
	CONVERT(VARCHAR(12),
	V.DATAOCORRENCIA,
	103) AS DATAOCORRENCIA,
	V.NUMVEICULO,
	T.TIPOVEICULO,
	V.TOTALDEEIXOS
FROM
	TABVEICULOSENVOLVIDOS V
	LEFT JOIN TAUXTIPOSVEICULOS T
	ON V.CODTIPOVEICULO = T.CODTIPOVEICULO
WHERE
	V.DATAOCORRENCIA BETWEEN '2010-01-01'
	AND DATEADD(DAY,
	-1,
	GETDATE())
ORDER BY
	NUMOCORRENCIA