--consulta para trazer ocorrencias com animais--
SELECT
    T.NUMOCORRENCIA,
    CONVERT(VARCHAR(12),
    T.DATAOCORRENCIA,
    103) AS DATAOCORRENCIA,
    A.ANIMAL,
    T.QTD,
    A.PORTE,
    A.GENERO
FROM
    TABANIMAIS T
    LEFT JOIN TAUXANIMAIS A
    ON T.CODANIMAL = A.CODANIMAL
WHERE
    T.DATAOCORRENCIA BETWEEN '2023-01-01'
    AND DATEADD(DAY, -1, GETDATE())
ORDER BY
    DATAOCORRENCIA,
    NUMOCORRENCIA