--consulta de acidentes
SELECT
    CONCAT(T.NUMOCORRENCIA,
	'-',
	CONVERT(VARCHAR(12),
	T.DATAOCORRENCIA,
	103)) AS IDOCORRENCIA,
    T.NUMOCORRENCIA,
    CONVERT(VARCHAR(12),
    T.DATAOCORRENCIA,
    103) AS DATAOCORRENCIA,
    O.TIPOOCORRENCIA AS SUBTIPOOCORRENCIA,
    AC.TIPOACIDENTE,
    AC.RELCLASS AS CLASSE,
    CP.CAUSAPROVAVEL,
    CM.CONDICAOMETEOROLOGICA,
    CV.CONDICAOVISIBILIDADE,
    PP.DESCRICAO AS PERFILPISTA
FROM
    TABOCORRENCIAS T
    LEFT JOIN TABACIDENTES A
    ON A.NUMOCORRENCIA = T.NUMOCORRENCIA
    AND A.DATAOCORRENCIA = T.DATAOCORRENCIA
    LEFT JOIN TAUXTIPOSOCORRENCIAS O
    ON T.CODTIPOOCORRENCIA = O.CODTIPOOCORRENCIA
    LEFT JOIN TAUXTIPOSACIDENTES AC
    ON AC.CODTIPOACIDENTE = A.CODTIPOACIDENTE
    LEFT JOIN TAUXCAUSASPROVAVEIS CP
    ON CP.CODCAUSAPROVAVEL = A.CODCAUSAPROVAVEL
    LEFT JOIN TAUXCONDICOESMETEOROLOGICAS CM
    ON CM.CODCONDICAOMET = A.CODCONDICAOMET
    LEFT JOIN TAUXCONDICOESVISIBILIDADE CV
    ON CV.CODCONDICAOVIS = A.CODCONDICAOVIS
    LEFT JOIN TAUXANIMAISPERFILPISTA PP
    ON PP.CODPERFILPISTA = A.PERFILPISTA
WHERE
    T.DATAOCORRENCIA BETWEEN '2010-01-01' AND DATEADD(DAY, -1, GETDATE())
    AND O.TIPOOCORRENCIA IN ('AC1',
    'AC2',
    'AC3')
 -- Adicionada cláusula WHERE para filtrar as linhas desejadas
ORDER BY
    DATAOCORRENCIA,
    NUMOCORRENCIA;